### PR TITLE
Reject empty operand in cd built-in

### LINKED ISSUE #104: Reject an empty operand in the `cd` built-in
POSIX.1-2024 requires that the `cd` built-in fail if given an empty operand as in `cd ''`.

Currently, `cd -L ''` is effectively equivalent to `cd -L "$PWD/"`, which usually results in successfully not changing the working directory.

- [ ] Update the implementation to add a check for an empty operand. The exit status should be 5 on error.
- [ ] Update the test scripts.
- [ ] Update the user manual.
- [ ] Update the `NEWS`.

### PR DESCRIPTION
**Pull request by c0d3-br3ak9r**
Made the following changes:
- [x] Update the implementation to add a check for an empty operand. The exit status should be 5 on error.
- [x] Update the test scripts.
- [x] Update the user manual.
- [x] Update the NEWS.

Fixes #104

### CODE REVIEW

File: path.c [hunk 1]
```diff
@@ -1232,6 +1232,11 @@ int change_directory(
 
     assert(!logical || !ensure_pwd);
 
+    if ( newpwd[0] == L'\0' ) {
```
Comment (magicant) [inline path.c]: Although we don't have an explicit coding style guide, we usually don't put spaces inside parentheses.

```suggestion
    if (newpwd[0] == L'\0') {
```

File: path.c [hunk 2]
```diff
@@ -1232,6 +1232,11 @@ int change_directory(
...
+	xerror(0, Ngt("empty directory"));
```
Comment (magicant) [inline path.c]: Thanks for adding the new message, but "empty directory" might sound like the directory has no files in it, rather than the directory name being zero length. How about "empty directory name"?

```suggestion
	xerror(0, Ngt("empty directory name"));
```

**Review by magicant — COMMENTED** [review]
Thanks!

File: path.c (hunk 2 above)
Comment (c0d3-br3ak9r) [reply path.c]: Yes, you're right. "empty directory name" sounds better

**Comment by c0d3-br3ak9r** [comment]
Hi, I've resolved the comments. Let me know if you need anything more.

File: tests/cd-y.tst [hunk 3]
```diff
@@ -18,16 +18,11 @@ __IN__
...
-unset CDPATH
+test_Oe -e 5 'empty operand'
 cd ''
-echo ---
-pwd
 __IN__
----
-$ORIGPWD
-__OUT__
+cd: empty directory
```
Comment (magicant) [inline tests/cd-y.tst]: Let's update here as well to match the new error message.
```suggestion
cd: empty directory name
```

**Review by magicant — APPROVED** [review]
Great. Thanks!
